CSRF_PROTECTION = False
DOCUMENTS_PER_PAGE = 20
SECRET_KEY = "some_secret_key"
FLASK_APP_SETTINGS = {
    "SESSION_COOKIE_NAME": "conductor_sid"
}
PORT = 3000
STATIC_FOLDER = "static"
ACTION_LOGGING = True

SESSIONS_AUTO_CLEANUP = True
SESSIONS_AUTO_CLEANUP_RAND_TRIGGER = 0.05

DEFAULT_GROUP_POSTFIX = "_unknown"

SECURITY_KEY_TTL = 600

