CSRF_PROTECTION = False
DOCUMENTS_PER_PAGE = 20
SECRET_KEY = "some_secret_key"
FLASK_APP_SETTINGS = {
    "SESSION_COOKIE_NAME": "inventoree_sid"
}
PORT = 3000
STATIC_FOLDER = "static"
AUTHORIZER = "SysAuthorizer"
ACTION_LOGGING = True

SESSIONS_AUTO_CLEANUP = True
SESSIONS_AUTO_CLEANUP_RAND_TRIGGER = 0.05

GRAVATAR_PATH = "https://sys.mail.ru/avatar/internal"
DEFAULT_GROUP_POSTFIX = "_unknown"

SECURITY_KEY_TTL = 600
