CSRF_PROTECTION = False
DOCUMENTS_PER_PAGE = 20
SECRET_KEY = "some_secret_key"
FLASK_APP_SETTINGS = {
    "SESSION_COOKIE_NAME": "inventoree_sid"
}
PORT = 3000
STATIC_FOLDER = "static"
AUTHORIZER = "LocalAuthorizer"
ACTION_LOGGING = True
DEFAULT_GROUP_POSTFIX = "_unknown"
